import React from 'react';

export type DisplayState =
  | 'NOT_STARTED'
  | 'DRAFT'
  | 'SUBMITTED'
  | 'IN_REVIEW'
  | 'RETURNED'
  | 'APPROVED'
  | 'OVERDUE'
  | 'CANCELLED'
  | 'EXPIRED'
  | 'PURGED'
  | string;

interface StatusBadgeProps {
  state: DisplayState;
  isOverdue?: boolean;
  className?: string;
}

interface StatusVisual {
  label: string;
  badgeClass: string;
  dotClass: string;
  pulse?: boolean;
}

// 07-design-system.md §1 defines the --status-* tokens consumed below (bg-status-*/text-status-*
// are generated by @theme inline in globals.css). CANCELLED has no dedicated token in that doc
// yet, so it borrows the neutral "draft" tone -- flag to design if a distinct one is warranted.
const STATUS_VISUALS: Record<string, StatusVisual> = {
  APPROVED: {
    label: 'Approved',
    badgeClass: 'bg-status-approved/10 text-emerald-800 border-status-approved/30',
    dotClass: 'bg-status-approved',
  },
  IN_REVIEW: {
    label: 'In Review',
    badgeClass: 'bg-status-in-review/10 text-amber-800 border-status-in-review/30',
    dotClass: 'bg-status-in-review',
    pulse: true,
  },
  SUBMITTED: {
    label: 'Submitted',
    badgeClass: 'bg-status-submitted/10 text-blue-800 border-status-submitted/30',
    dotClass: 'bg-status-submitted',
  },
  RETURNED: {
    label: 'Returned',
    badgeClass: 'bg-status-returned/10 text-rose-800 border-status-returned/30',
    dotClass: 'bg-status-returned',
  },
  DRAFT: {
    label: 'Draft',
    badgeClass: 'bg-status-draft/10 text-slate-700 border-status-draft/30',
    dotClass: 'bg-status-draft',
  },
  EXPIRED: {
    label: 'Expired',
    badgeClass: 'bg-status-overdue/10 text-red-800 border-status-overdue/30',
    dotClass: 'bg-status-overdue',
  },
  CANCELLED: {
    label: 'Cancelled',
    badgeClass: 'bg-status-draft/10 text-slate-700 border-status-draft/30',
    dotClass: 'bg-status-draft',
  },
  // FR-23 / 03-design-spec.md: a purged submission's file is gone but its approval record
  // survives -- this must never read as "Not Started", which tells the intern nothing was
  // ever submitted.
  PURGED: {
    label: 'Deleted',
    badgeClass: 'bg-status-deleted/10 text-slate-600 border-status-deleted/30',
    dotClass: 'bg-status-deleted',
  },
  NOT_STARTED: {
    label: 'Not Started',
    badgeClass: 'bg-status-not-started/10 text-gray-600 border-status-not-started/30',
    dotClass: 'bg-status-not-started',
  },
};

export function StatusBadge({ state, isOverdue, className = '' }: StatusBadgeProps) {
  if (isOverdue && state !== 'APPROVED' && state !== 'PURGED') {
    return (
      <span
        className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold bg-red-100 text-red-800 border border-red-200 ${className}`}
      >
        <span className="h-1.5 w-1.5 rounded-full bg-red-600" aria-hidden="true" />
        Overdue
      </span>
    );
  }

  const visual = STATUS_VISUALS[state] || STATUS_VISUALS.NOT_STARTED;

  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold border ${visual.badgeClass} ${className}`}
    >
      <span
        className={`h-1.5 w-1.5 rounded-full ${visual.dotClass} ${visual.pulse ? 'motion-safe:animate-pulse' : ''}`}
        aria-hidden="true"
      />
      {visual.label}
    </span>
  );
}
